### PR TITLE
Portfolio: Desktop version

### PR DESCRIPTION
**Pull request by faisalakb**
Please check my PR. I added and updated the following features on this branch :

-Use media queries to achieve responsiveness. 👍 
-Design desktop and mobile versions. 👍 
- Add different aspect ratio background images for different screens. 👍 
- For desktop, use Desktop: >=768px. 👍 
- Use grid and flexbox for responsiveness. 👍

### CODE REVIEW

**Review by divinecharlotte — CHANGES_REQUESTED** [review]
Hi @faisalakb  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive commit messages ✔️ 
- clean code ✔️ 
- Descriptive PR ✔️ 




## Required Changes ♻️

- [ ] kindly consider adding an existing Twitter account if you have one and if you don't have one yet consider creating it or removing its handle this will make your readme look more professional 😃 

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
Sir @divinecharlotte  kindly check. I updated the above comments.

**Review by TadesseDev — APPROVED** [review]
### Hi @faisalakb 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
giphy (1)



## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by faisalakb** [comment]
Thanks for your lovely comments.

**Pull request merged**
