### PR TITLE
Portfolio: details popup window

### PR DESCRIPTION
**Pull request by faisalakb**
Please check my PR. I updated the following features in my portfolio:
- Popup window appears when clicking on the SeeProject button on desktop and mobile.
- The content of the popup window dynamically loads using Javascript.

### CODE REVIEW

**Review by souad988 — COMMENTED** [review]
Hi @faisalakb , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly remove all default text under each section in your README and customize with your own content this is important to make your work professional 
_Also check the JavaScript linter setup steps in your lesson as I don't see it's check in github 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by faisalakb** [comment]
Please check i updated all above comments.

**Review by uwadonat — APPROVED** [review]
## Hi @faisalakb,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Professional readme file ✔️
- Amazing design ✔️
- Well organized and clean code ✔️
- No linter errors ✔️
- Your deployed version works as expected ✔️
thanks-awesome

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by faisalakb** [comment]
Thanks for the time, sir.

**Pull request merged**
